name: Build Android APK

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          echo "EXPO_PUBLIC_SUPABASE_URL=${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}" >> .env
          echo "EXPO_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }}" >> .env

      - name: Prebuild Android
        run: npx expo prebuild --platform android --clean

      - name: Build Android APK
        working-directory: ./android
        run: ./gradlew assembleRelease --no-daemon

      - name: Sign APK
        if: success()
        run: |
          APK_PATH="android/app/build/outputs/apk/release/app-release-unsigned.apk"
          SIGNED_APK_PATH="kidopedia-${{ github.sha }}.apk"

          if [ -f "$APK_PATH" ]; then
            mv "$APK_PATH" "$SIGNED_APK_PATH"
          else
            echo "APK not found at expected path"
            find android/app/build/outputs -name "*.apk"
            exit 1
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: kidopedia-${{ github.sha }}
          path: kidopedia-${{ github.sha }}.apk
          retention-days: 30

      - name: Build Summary
        if: always()
        run: |
          echo "### Build Complete!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Download the APK from the artifacts section above." >> $GITHUB_STEP_SUMMARY
