import { Achievement } from '@/types/profile';

/**
 * Built-in achievements that are seeded into the local SQLite database on
 * first launch. The IDs are stable UUIDs so they can also be matched against
 * the Supabase achievements table if needed.
 */
export const BUILT_IN_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-first-word',
    code: 'first_word',
    title: 'First Word!',
    description: 'Looked up your very first word.',
    icon: '🌟',
    category: 'words',
    unlock_condition: { words_learned: 1 },
  },
  {
    id: 'ach-five-words',
    code: 'five_words',
    title: 'Word Collector',
    description: 'Learned 5 words. Keep going!',
    icon: '📚',
    category: 'words',
    unlock_condition: { words_learned: 5 },
  },
  {
    id: 'ach-ten-words',
    code: 'word_explorer',
    title: 'Word Explorer',
    description: 'Discovered 10 words.',
    icon: '🔍',
    category: 'words',
    unlock_condition: { words_learned: 10 },
  },
  {
    id: 'ach-25-words',
    code: 'vocabulary_star',
    title: 'Vocabulary Star',
    description: 'Learned 25 words — you\'re a star!',
    icon: '⭐',
    category: 'words',
    unlock_condition: { words_learned: 25 },
  },
  {
    id: 'ach-50-words',
    code: 'word_wizard',
    title: 'Word Wizard',
    description: 'Mastered 50 words. Magical!',
    icon: '🧙',
    category: 'words',
    unlock_condition: { words_learned: 50 },
  },
  {
    id: 'ach-100-words',
    code: 'century_reader',
    title: 'Century Reader',
    description: 'Learned 100 words. Incredible!',
    icon: '💯',
    category: 'words',
    unlock_condition: { words_learned: 100 },
  },
  {
    id: 'ach-500-words',
    code: 'word_master',
    title: 'Word Master',
    description: 'Learned 500 words. You\'re amazing!',
    icon: '🏆',
    category: 'words',
    unlock_condition: { words_learned: 500 },
  },
  {
    id: 'ach-first-favorite',
    code: 'first_favorite',
    title: 'Bookmarked!',
    description: 'Saved your first favorite word.',
    icon: '❤️',
    category: 'exploration',
    unlock_condition: { favorites_count: 1 },
  },
  {
    id: 'ach-ten-favorites',
    code: 'collector',
    title: 'Word Collector',
    description: 'Saved 10 favorite words.',
    icon: '💾',
    category: 'exploration',
    unlock_condition: { favorites_count: 10 },
  },
  {
    id: 'ach-streak-3',
    code: 'streak_3',
    title: '3-Day Streak!',
    description: 'Learned words 3 days in a row.',
    icon: '🔥',
    category: 'streak',
    unlock_condition: { streak_count: 3 },
  },
  {
    id: 'ach-streak-7',
    code: 'streak_7',
    title: 'Week Warrior',
    description: 'Learned words every day for a week!',
    icon: '🏅',
    category: 'streak',
    unlock_condition: { streak_count: 7 },
  },
  {
    id: 'ach-streak-30',
    code: 'streak_30',
    title: 'Monthly Master',
    description: 'Incredible! 30-day learning streak!',
    icon: '👑',
    category: 'streak',
    unlock_condition: { streak_count: 30 },
  },
  {
    id: 'ach-level-2',
    code: 'level_up',
    title: 'Level Up!',
    description: 'Reached Level 2.',
    icon: '⬆️',
    category: 'words',
    unlock_condition: { level: 2 },
  },
  {
    id: 'ach-level-5',
    code: 'scholar',
    title: 'Scholar',
    description: 'Reached Level 5. You\'re a scholar!',
    icon: '🎓',
    category: 'words',
    unlock_condition: { level: 5 },
  },
  {
    id: 'ach-level-10',
    code: 'genius',
    title: 'Genius',
    description: 'Reached Level 10. Pure genius!',
    icon: '🧠',
    category: 'words',
    unlock_condition: { level: 10 },
  },
];
